[tool.poetry]
name = "restful_intro"
version = "0.1.0"
description = ""
authors = ["George Richards <georich@protonmail.com>"]

[tool.poetry.dependencies]
python = "*"
flask = "^1.0"
flask-restful = "^0.3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
